# In this file there are a few RBAC objects to be used by the sensor and by the workflow.
# The sensor uses the operate-workflow-sa service account, which has a role that allows it to operate on workflows.
# The workflow uses the execute-workflow-sa service account, which has a role that allows it to get, list, watch, and patch namespaces and pods.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: operate-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: execute-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: execute-workflow-role
rules:
  - apiGroups:
      - ""
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
    resources:
      - namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: execute-workflow-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: execute-workflow-role
subjects:
  - kind: ServiceAccount
    namespace: argo-events
    name: execute-workflow-sa

---

